### 基本理解

In [15]:
# データの読み込み
import pandas as pd 
excel = pd.ExcelFile("C:/Users/1109685/Documents/IR/Sample_freejob.xlsx")

DataFrameの構成要素
- values：Numpy配列
- 列名columns
- 行名index

In [21]:
df=pd.read_excel(excel, sheet_name=0)
print(df.shape[0],df.shape[1])
print(df.columns)

282 373
Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 363', 'Unnamed: 364', 'Unnamed: 365', 'Unnamed: 366',
       'Unnamed: 367', 'Unnamed: 368', 'Unnamed: 369', 'Unnamed: 370',
       'Unnamed: 371', 'Unnamed: 372'],
      dtype='object', length=373)

In [10]:
df.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 363,Unnamed: 364,Unnamed: 365,Unnamed: 366,Unnamed: 367,Unnamed: 368,Unnamed: 369,Unnamed: 370,Unnamed: 371,Unnamed: 372
0,NaN,FREEJOB予算表,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,◆重要指数,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,12,NaN,1,NaN,2,NaN,3,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,着地,予算,着地,予算,着地,予算,着地,予算,着地,NaN
5,1,獲得数計,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1009,1024,1024,1039,1039,1054,1054,1069,1069,1
6,2,NaN,レギュラー,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,615,625,625,635,635,645,645,655,655,2
7,3,NaN,アドバンス,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,381,386,386,391,391,396,396,401,401,3
8,4,NaN,バリュー,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
9,5,NaN,アルバイト,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,5

In [23]:
! env:HTTP_PROXY="http://proxy:8080"

! env:HTTPS_PROXY="http://proxy:8080"

�t�@�C�����A�f�B���N�g�����A�܂��̓{�����[�� ���x���̍\�����Ԉ���Ă��܂��B
�t�@�C�����A�f�B���N�g�����A�܂��̓{�����[�� ���x���̍\�����Ԉ���Ă��܂��B

In [ ]:
# 生成AI系のインポート
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

llm=ChatOpenAI(model="gpt-4.1-nano")
prompt=ChatPromptTemplate.from_messages([
    ("system", "あなたは優秀なデータ分析者です。"),
    ("human", "以下のデータを分析してください。\n"
             "データの内容は{data}です。\n"
             "この表には複数の表構造が含まれています。\n"
            #  "【重要指数】、【PL】、【指標】の各表の行数と列数を教えてほしい。\n"
            #  "回答形式は「重要指数：〇×〇, PL：〇×〇、指標：〇×〇」のようにしてください。\n"
            #  "回答形式を必ず守ってください。\n"
             "重要指数の表に含まれる行タイトルをすべて教えてください。\n"
             "大分類・中分類を含むような場合は、最も小さい分類まで表示してください。\n"
             "小分類とは、◆重要指数の表構造でいうと、「レギュラー」「アドバンス」のような分類のことです。\n"
             "回答のみを表示してください。\n")
])

chain=prompt | llm

result=chain.invoke({"data":df.to_dict()})
print(result.content)

content='・「◆重要指数」\n・「獲得数計」\n・「解約数」\n・「解約率」\n・「ジョブレポ保有数」\n・「ジョブレポ解約数」\n・「ジョブレポ解約率」\n・「アドバンス比率」\n・「稼働人数」\n・「派遣人数」\n・「【PL】」\n・「売上」\n・「獲得コスト」\n・「ストックCF」\n・「【指標】」\n・「将来収益込利益(5年)」\n・「5年事業利回り」\n・「累計将来込利益」\n・「ストックアップ」\n・「【財務】」\n・「【指標】」\n・「【資産】」\n・「【負債】」\n・「【純資産】」\n・「【資産・負債・純資産】（詳細不明）」' additional_kwargs={'refusal': None} response_metadata={'token_usage': {'completion_tokens': 204, 'prompt_tokens': 730402, 'total_tokens': 730606, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 730240}}, 'model_name': 'gpt-4.1-nano-2025-04-14', 'system_fingerprint': 'fp_6bb38829ab', 'id': 'chatcmpl-BXjYnpm6FRtlbRIUbvLI3lzyWgT9D', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None} id='run--e93cf4fc-25b7-4aa3-8ef9-3bdcf76d2e3d-0' usage_metadata={'input_tokens': 730402, 'output_tokens': 204, 'total_tokens': 730606, 'input_token_details': {'audio': 0, 'cache_read': 730240}, 'output_token_details': {'audio': 0, 'reasoning': 0}}